### PR TITLE
Prepare 0.5.0 release

### PR DESCRIPTION
**Pull request by Aeilert**
* Bump version
* Fix URL bug
* Bump roxygen2 version

### CODE REVIEW

**Comment by ohjakobsen** [comment]
@Aeilert: We need to add `@return`/`@returns` and `@examples` to all exported functions before submitting. Most other checks seem to be OK for the moment. See [this page](https://r-pkgs.org/release.html) for details.

**Comment by ohjakobsen** [comment]
I've added examples and return values to exported functions and have fixed a couple of bugs. @Aeilert: can you go through a last time to check if we have missed anything?

**Comment by Aeilert** [comment]
> I've added examples and return values to exported functions and have fixed a couple of bugs. @Aeilert: can you go through a last time to check if we have missed anything?

Hi @ohjakobsen. I made a few minor changes in the documentation, particularly to standardise how examples are written across different functions. I also converted the `run_pioneer()` example to a `dontrun{}` variant. The main reason for this is that the app would spin up when running `devtools::run_examples()` making a bit tricky to check all the examples in a simple manner. 

Otherwise I think everything looks good. :)

**Comment by ohjakobsen** [comment]
CRAN might balk at `\dontrun`, but I agree in principle. Let's go for submitting the package!

**Review by ohjakobsen — APPROVED** [review]
pioneeR has been accepted and published on CRAN!

**Pull request merged**
